### ISSUE TITLE
profile.html 충돌

### ISSUE THREAD

**Issue by JSPlike** [JSPlike/hanco_rails#13]
<img width="700" alt="2018-09-04 11 03 18" src="https://user-images.githubusercontent.com/25076970/45006105-3642c900-b032-11e8-98cc-d2192f14619d.png">

그림보고 충돌 해결

master에서 fetch해서 병합 전 상태로 만들고

충돌확인 후에

충돌 난 섹터 제거

재 병합

**Comment by khb1109** [comment]
일단 머지 완료
충돌은 log파일에서 나와서 이상없었음

**Comment by JSPlike** [comment]
확인!
