### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by JSPlike** [JSPlike/hanco_rails#3]
<img width="1007" alt="2018-08-28 12 14 15" src="https://user-images.githubusercontent.com/25076970/44668040-677e3080-aa57-11e8-864b-941ae841f675.png">

이거 빠르게 잡아줄래??

**Comment by khb1109** [comment]
@project = User.projects
@projects = current_user.projects로 변경해서 푸시할게~

**Comment by JSPlike** [comment]
확인!
